version: "3"

services:

  db:
    image: mysql:5.7
    restart: "no"
    volumes:
      - dockerpress_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - dockerpress

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4
    restart: "no"
    volumes:
      - dockerpress_volume:/var/www/html/
      - ./theme:/var/www/html/wp-content/themes/wp-starter
      - ./plugins:/var/www/html/wp-content/plugins
      - ./languages:/var/www/html/wp-content/languages
      - ./uploads:/var/www/html/wp-content/uploads
      - ./vendor:/var/www/html/vendor
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      # WORDPRESS_TABLE_PREFIX: pr19_
      #WORDPRESS_CONFIG_EXTRA:
      #  define( 'WP_DEBUG', true );
    ports:
      - 9099:80
    networks:
      - dockerpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: "no"
    ports:
      - 9299:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 3000000000
    networks:
      - dockerpress

networks:
  dockerpress:

volumes:
  dockerpress_volume:
  dockerpress_db_data: